### ISSUE TITLE
Feature Request: Backup all

### ISSUE THREAD

**Issue by timobeuker** [brian1917/workloader#102]
Hi Brian,

I've created a script which exports me all data once per day.
It is quite useful for us because we are using the cloud-version and so we don't have the posibility to make Database-backups by our own (and its requested by the Security)

so i wrote the following script and run it daily:
`#bin/bash
workdir='/app/illumio/workloader/linux_amd64-v9.12.6'
d=`date +%Y%m%d_%H%M%S`
echo "Workdir: "$workdir
echo "Date: "$d
cd $workdir
./workloader wkld-export
./workloader ven-export
./workloader ipl-export
./workloader label-export
./workloader labelgroup-export
./workloader label-dimension-export
./workloader svc-export
./workloader ruleset-export
./workloader rule-export
./workloader eb-export
./workloader cwp-export
mkdir $workdir/exports/$d
mv $workdir/workloader-* $workdir/exports/$d/
`

maybe it is possible to add something similar to your workloader ;)
Best Regards
Timo

**Comment by brian1917** [comment]
@timobeuker  - thanks for the suggestion. I am tagging this as future review so we can come back to it in the future and potentially add it. For now, I'm going to keep this as something you'd use a bash wrapper script for like you did.
