### ISSUE TITLE
Enhance Traffic Export to support Date Time precision on Start and End parameters

### ISSUE THREAD

**Issue by fwalton-tm** [brian1917/workloader#106]
The Traffic extract has a minimum timespan of one day since time portions of the "-s" and "-e" parameter values are truncated.
Providing the additional precision will allow smaller extracts that are not subject to the system data extract limitations.

The necessary code changes appear to be confined to the cmd\traffic\Traffic.go file.
Existing:
30  TrafficCmd.Flags().StringVarP(&start, "start", "s", time.Now().AddDate(0, 0, -88).In(time.UTC).Format("2006-01-02"), "start date in the format of yyyy-mm-dd.")
107 tq.StartTime, err = time.Parse("2006-01-02 MST", fmt.Sprintf("%s %s", start, "UTC"))
114 	tq.EndTime, err = time.Parse("2006-01-02 15:04:05 MST", fmt.Sprintf("%s 23:59:59 %s", end, "UTC"))

Proposed:
30 TrafficCmd.Flags().StringVarP(&start, "start", "s", time.Now().AddDate(0, 0, -88).In(time.UTC).Format("2006-01-02 15:04:05"), "start date in the format of yyyy-mm-ddTHH:mm:ss GMT.")
107 tq.StartTime, err = time.Parse("2006-01-02 15:04:05 MST", fmt.Sprintf("%s %s", start, "UTC"))
114 tq.EndTime, err = time.Parse("2006-01-02 15:04:05 MST", fmt.Sprintf("%s %s", end, "UTC"))

**Comment by brian1917** [comment]
@fwalton-tm - this has been addressed in the latest commit/release: [567cbf0](https://github.com/brian1917/workloader/commit/567cbf0be4bae1f206894a18bcc23a4b249eed1e)
