### ISSUE TITLE
Allow svc-import to update service name

### ISSUE THREAD

**Issue by xmlisnotaprotocol** [brian1917/workloader#43]
svc-import won't detect/update the service name field on an existing (by HREF) svc, eg rename "IST common telnet" to "S-Telnet" will report back "nothing to be done"

./workloader.exe svc-import workloader-svc-import.csv
2022-10-11 10:06:59  [INFO] - nothing to be done.
2022-10-11 10:06:59  [INFO] - svc-import completed

**Comment by brian1917** [comment]
@xmlisnotaprotocol  - this has been incorporated using the `--meta` or `-m` flag on `svc-import`.
