### ISSUE TITLE
Feature Request: Add Labels in ven-export as in wkld-export 

### ISSUE THREAD

**Issue by ansred** [brian1917/workloader#52]
Feature Request: Add Labels in `ven-export` as in `wkld-export` 

Currently, you can view/filter workloads based on labels only in `wkld-export`

However, you can't do that with `ven-export` report 

Reasons why need that:
- For large customers, it's important to be able to filter workloads/vens based on labels for automation and organizational purposes 
- **ven-export** report has important data that is not available **wkld-export**, such as (_uid_ + _ven health_ + _ven type_)
- ven type specifically is important with the new updatres from Illumio and introducing Endpoint vs Server
- uid is important to help troubleshoot cloned workloads

**Comment by brian1917** [comment]
completed
