### ISSUE TITLE
Feature Request: Create folders automatically when running workloader command

### ISSUE THREAD

**Issue by ansred** [brian1917/workloader#54]
Subject:
Feature Request: Create folders automatically when running workloader command

Current flow:
Currently whenever you run workloader it generate files/exported output on the home directory 

Request:
It would be great have a folder creation on the home directory with the and have the following structure

Workloader Folder >> output Folder >> FQDN Folder >> Date Folder >> csv/json files

Example Screenshot:
<img width="1231" alt="Screenshot 2022-12-22 at 1 14 06 PM" src="https://user-images.githubusercontent.com/5244872/209199516-4c4b24bb-f7af-47db-bdd7-1811ceb689d4.png">

Benefit of the change:
It's easier to navigate and locate files and if needed to setup a cron job to do these jobs and have it organized in folder structure.

**Comment by brian1917** [comment]
@ansred - thanks for the feedback. this has been tagged as future review. not something planning to do now, but will review in the future.
