### ISSUE TITLE
Feature Request: Instruction Set for manually compiling workloader source code available in the project

### ISSUE THREAD

**Issue by mustangint1** [brian1917/workloader#59]
Brian, 

Is it possible to get an instruction set for compiling workloader source code on the project here, or is all of the workloader source code in your specific project.  I know there are a few other devs' that are working on your project.

If not posssible, please let us know.

**Comment by brian1917** [comment]
@mustangint1 - you can absolutely clone/download the repo and build workloader from scratch.

From the root directory running `go build` should build the executable for the OS you run the build from. You can use the `GOOS` and `GOARCH` command line variables to set the build for other operating systems or architectures.

You can also checkout the `.github/workflows/workloader-release.yml` file to see the commands that are used for the release builds. These commands take in a few build flags to set variables and last commit.

For example, this will mimic a release build:
```
go build -ldflags "-X github.com/brian1917/workloader/utils.Version=$(cat version) -X github.com/brian1917/workloader/utils.Commit=$(git rev-list -1 HEAD)"
```
