### ISSUE TITLE
Use Case Request - Is it possible to get this compiled for Linux ARM?

### ISSUE THREAD

**Issue by mustangint1** [brian1917/workloader#60]
Hello Brian, 

This is a one off, but due to the time it takes to run some of these reports, is it possible to get a compiled Linux ARM version so it can be put on a arm Linux system, and run?

Thanks

**Comment by brian1917** [comment]
@mustangint1 - as of 9.7.5 the releases will include ARM and AMD64 options.

**Comment by mustangint1** [comment]
Thanks Brian
