### ISSUE TITLE
Bug:  Any error message stops workloader processing of function.

### ISSUE THREAD

**Issue by mustangint1** [brian1917/workloader#61]
Brian, 

This happens in all versions upto this point.  Reguardless of the function called by workloader when it finds something it can not process, the error occurs and all processing stops.  I recommend keeping the error message in the workloader.log, however allow workloader to continue processing the requested job such as ven-export, or whatever function it calls.  It is cumbersome to have to keep rerunning workloader when this happens.  

user@linuxbox:~/linux-v9.5.1$ cat workloader.log
-----------------------------------------------------------------------------
2023-03-21 16:55:14 [INFO] - workloader version 9.5.1 - started wkld-export
2023-03-21 16:55:14 [INFO] - using default pce - defaultname - 22.5.10-95
2023-03-21 16:59:08 [INFO] - output file: workloader-wkld-export-20230321_165907.csv
2023-03-21 16:59:08 [INFO] - 58556 workloads exported
2023-03-21 16:59:08 [INFO] - wkld-export completed
-----------------------------------------------------------------------------
2023-03-21 16:59:16 [INFO] - workloader version 9.5.1 - started ven-export
2023-03-21 16:59:16 [INFO] - using default pce - defaultname - 22.5.10-95
2023-03-21 17:08:37 [ERROR] - /orgs/numberhere/vens/HREFListing - workstation name - associated workload does not exist

**Comment by brian1917** [comment]
@mustangint1 - this behavior is as designed to make sure people don't trigger actions in the PCE they don't expect. For some commands I can see how it would be a pain to always err on the conservative side of stopping execution on an error.

In version 9.7.6 I added two things:
1. A global flag that can be used on any command: `continue-on-errror`. This flag makes it so any error does not also exit the execution. It will still log the error as an error but it will functionally behave like a warning as it will continue to run.
2. A command `error-default` where you can set your default behavior to `continue` or `stop`. If you run `workloader error-default continue` it will be like using the `continue-on-error` flag all the time. I put this in for if you do want that behavior all the time you don't always need to use the flag.

Hope that helps.

**Comment by mustangint1** [comment]
It does Brian, thank you for working that in.  That will be a huge help on
these reports.
