### ISSUE TITLE
Workloader stalls out on any command to the PCE

### ISSUE THREAD

**Issue by S4lmify** [brian1917/workloader#68]
Workloader just stalls out when doing simple commands like "workloader wkld-export" however endpoint and PCE complete successful TCP handshake and wireshark looks good.

**Comment by brian1917** [comment]
@S4lmify - this sounds like an environmental issue. I'd suspect there is some proxy in play where some communication is proxied and the workloader communication is not. You can set workloader proxy explicitly in the settings `workloader set-proxy` command.
