### ISSUE TITLE
Go installation not working

### ISSUE THREAD

**Issue by Maxximouss** [brian1917/workloader#79]
Hello,
I follow instructions to install workloader with Go.
I had to use this command line to install it "go install github.com/brian1917/workloader@latest"
But after that I cannot use workloader command. Did I miss something?

Here is my go env
`> go env
GO111MODULE=''
GOARCH='amd64'
GOBIN=''
GOCACHE='/home/max/.cache/go-build'
GOENV='/home/max/.config/go/env'
GOEXE=''
GOEXPERIMENT=''
GOFLAGS=''
GOHOSTARCH='amd64'
GOHOSTOS='linux'
GOINSECURE=''
GOMODCACHE='/home/max/go/pkg/mod'
GONOPROXY=''
GONOSUMDB=''
GOOS='linux'
GOPATH='/home/max/go'
GOPRIVATE=''
GOPROXY='https://proxy.golang.org,direct'
GOROOT='/usr/local/go'
GOSUMDB='sum.golang.org'
GOTMPDIR=''
GOTOOLCHAIN='auto'
GOTOOLDIR='/usr/local/go/pkg/tool/linux_amd64'
GOVCS=''
GOVERSION='go1.21.0'
GCCGO='gccgo'
GOAMD64='v1'
AR='ar'
CC='gcc'
CXX='g++'
CGO_ENABLED='1'
GOMOD='/usr/local/go/src/go.mod'
GOWORK=''
CGO_CFLAGS='-O2 -g'
CGO_CPPFLAGS=''
CGO_CXXFLAGS='-O2 -g'
CGO_FFLAGS='-O2 -g'
CGO_LDFLAGS='-O2 -g'
PKG_CONFIG='pkg-config'
GOGCCFLAGS='-fPIC -m64 -pthread -Wl,--no-gc-sections -fmessage-length=0 -ffile-prefix-map=/tmp/go-build3472462635=/tmp/go-build -gno-record-gcc-switches'
`

And an extract of my $PATH
`> echo $PATH
/usr/local/go/bin ... /usr/local/go/bin /home/max/go/bin`

**Comment by brian1917** [comment]
@Maxximouss  - can you run `which workloader` and see if workloader is registered anywhere in the `$PATH`

**Comment by Maxximouss** [comment]
@brian1917 
```bash
> which workloader
/home/max/go/bin/workloader
```

But in the meantime I installed workloader by cloning git and using the following commands : 
```bash
cd go/src/
mkdir github.com/
mkdir github.com/brian1917/
cd github.com/brian1917/
git clone git@github.com:brian1917/workloader.git
cd workloader/
go run main.go
go build -o workloader main.go
mv workloader ~/go/bin/
```
