### ISSUE TITLE
SIGSEGV cmd/labelexport.exportLabels()

### ISSUE THREAD

**Issue by agwilkinson** [brian1917/workloader#83]
$ **git describe --tags**
v10.0.4

$**./workloader label-export**
panic: runtime error: invalid memory address or nil pointer dereference
[signal **SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x9f900f**]

goroutine 1 [running]:
github.com/brian1917/workloader/cmd/labelexport.exportLabels()
	/home/foo/git/illumio/workloader/cmd/labelexport/cmd.go:92 +0x170f
github.com/brian1917/workloader/cmd/labelexport.glob..func1(0x12703c0?, {0xb56d67?, 0x0?, 0x0?})
	/home/foo/git/illumio/workloader/cmd/labelexport/cmd.go:46 +0x15d
github.com/spf13/cobra.(*Command).execute(0x12703c0, {0x12b9538, 0x0, 0x0})
	/home/foo/go/pkg/mod/github.com/spf13/cobra@v1.7.0/command.go:944 +0x847
github.com/spf13/cobra.(*Command).ExecuteC(0x126b060)
	/home/foo/go/pkg/mod/github.com/spf13/cobra@v1.7.0/command.go:1068 +0x3bd
github.com/spf13/cobra.(*Command).Execute(...)
	/home/foo/go/pkg/mod/github.com/spf13/cobra@v1.7.0/command.go:992
github.com/brian1917/workloader/cmd.Execute()
	/home/foo/git/illumio/workloader/cmd/root.go:241 +0x25
main.main()
	/home/foo/git/illumio/workloader/main.go:90 +0x709

$**dlv core workloader core**
Type 'help' for list of commands.
(dlv) **bt**
 0  0x0000000000468da1 in runtime.raise
    at /usr/local/go/src/runtime/sys_linux_amd64.s:159
 1  0x000000000044cda5 in runtime.dieFromSignal
    at /usr/local/go/src/runtime/signal_unix.go:870
 2  0x000000000044d33e in runtime.sigfwdgo
    at /usr/local/go/src/runtime/signal_unix.go:1086
 3  0x000000000044ba87 in runtime.sigtrampgo
    at /usr/local/go/src/runtime/signal_unix.go:432
 4  0x0000000000469086 in runtime.sigtramp
    at /usr/local/go/src/runtime/sys_linux_amd64.s:359
 5  0x00007f7d25630420 in ???
    at ?:-1
 6  0x0000000000437729 in runtime.crash
    at /usr/local/go/src/runtime/signal_unix.go:962
 7  0x0000000000437729 in runtime.fatalpanic
    at /usr/local/go/src/runtime/panic.go:1170
 8  0x0000000000436dfa in runtime.gopanic
    at /usr/local/go/src/runtime/panic.go:987
 9  0x000000000044cc76 in runtime.panicmem
    at /usr/local/go/src/runtime/panic.go:260
10  0x000000000044cc76 in runtime.sigpanic
    at /usr/local/go/src/runtime/signal_unix.go:835
**11  0x00000000009f900f in github.com/brian1917/workloader/cmd/labelexport.exportLabels
    at ./cmd/labelexport/cmd.go:92**
12  0x00000000009f78dd in github.com/brian1917/workloader/cmd/labelexport.glob..func1
    at ./cmd/labelexport/cmd.go:46
13  0x000000000083c5a7 in github.com/spf13/cobra.(*Command).execute
    at /home/foo/go/pkg/mod/github.com/spf13/cobra@v1.7.0/command.go:944
14  0x000000000083ce3d in github.com/spf13/cobra.(*Command).ExecuteC
    at /home/foo/go/pkg/mod/github.com/spf13/cobra@v1.7.0/command.go:1068
15  0x0000000000a5a865 in github.com/spf13/cobra.(*Command).Execute
    at /home/foo/go/pkg/mod/github.com/spf13/cobra@v1.7.0/command.go:992
16  0x0000000000a5a865 in github.com/brian1917/workloader/cmd.Execute
    at ./cmd/root.go:241
17  0x0000000000a5b629 in main.main
    at ./main.go:90
18  0x0000000000439a92 in runtime.main
    at /usr/local/go/src/runtime/proc.go:250
19  0x0000000000467441 in runtime.goexit
    at /usr/local/go/src/runtime/asm_amd64.s:1594
(dlv) 

(dlv) **frame 11**
> runtime.raise() /usr/local/go/src/runtime/sys_linux_amd64.s:159 (PC: 0x468da1)
Warning: debugging optimized function
Frame 11: ./cmd/labelexport/cmd.go:92 (PC: 9f900f)
    87:	
    88:			// Append to data slice
    89:			if noHref {
    90:				csvData = append(csvData, []string{l.Key, l.Value, l.CreatedBy.Href, l.CreatedAt, l.UpdatedBy.Href, l.UpdatedAt, l.ExternalDataSet, l.ExternalDataReference, strconv.FormatBool(l.LabelUsage.VirtualServer), strconv.FormatBool(l.LabelUsage.LabelGroup), strconv.FormatBool(l.LabelUsage.Ruleset), strconv.FormatBool(l.LabelUsage.StaticPolicyScopes), strconv.FormatBool(l.LabelUsage.PairingProfile), strconv.FormatBool(l.LabelUsage.Permission), strconv.FormatBool(l.LabelUsage.Workload), strconv.FormatBool(l.LabelUsage.ContainerWorkload), strconv.FormatBool(l.LabelUsage.FirewallCoexistenceScope), strconv.FormatBool(l.LabelUsage.ContainersInheritHostPolicyScopes), strconv.FormatBool(l.LabelUsage.ContainerWorkloadProfile), strconv.FormatBool(l.LabelUsage.BlockedConnectionRejectScope), strconv.FormatBool(l.LabelUsage.EnforcementBoundary), strconv.FormatBool(l.LabelUsage.LoopbackInterfacesInPolicyScopes), strconv.FormatBool(l.LabelUsage.VirtualService)})
    91:			} else {
**=>  92:				csvData = append(csvData, []string{l.Href, l.Key, l.Value, l.CreatedBy.Href, l.CreatedAt, l.UpdatedBy.Href, l.UpdatedAt, l.ExternalDataSet, l.ExternalDataReference, strconv.FormatBool(l.LabelUsage.VirtualServer), strconv.FormatBool(l.LabelUsage.LabelGroup), strconv.FormatBool(l.LabelUsage.Ruleset), strconv.FormatBool(l.LabelUsage.StaticPolicyScopes), strconv.FormatBool(l.LabelUsage.PairingProfile), strconv.FormatBool(l.LabelUsage.Permission), strconv.FormatBool(l.LabelUsage.Workload), strconv.FormatBool(l.LabelUsage.ContainerWorkload), strconv.FormatBool(l.LabelUsage.FirewallCoexistenceScope), strconv.FormatBool(l.LabelUsage.ContainersInheritHostPolicyScopes), strconv.FormatBool(l.LabelUsage.ContainerWorkloadProfile), strconv.FormatBool(l.LabelUsage.BlockedConnectionRejectScope), strconv.FormatBool(l.LabelUsage.EnforcementBoundary), strconv.FormatBool(l.LabelUsage.LoopbackInterfacesInPolicyScopes), strconv.FormatBool(l.LabelUsage.VirtualService)})**
    93:			}
    94:			stdOutData = append(stdOutData, []string{l.Href, l.Key, l.Value})
    95:		}
    96:	
    97:		if len(csvData) > 1 {
(dlv) 

(dlv) **locals**
csvData = [][]string len: 0, cap: 0, []
stdOutData = [][]string len: 161, cap: 256, [...]
labels = (**unreadable read out of bounds**)
err = error nil
a = github.com/brian1917/illumioapi.APIResponse {RespBody: "[{\"href\":\"/orgs/6/labels/281474976723681\",\"key\":\"app\",\"value\":\"A...+535820 more", StatusCode: 200, Header: net/http.Header [...],...+3 more}
newLabels = (**unreadable could not find loclist entry at 0x2be73e for address 0x9f900f**)
l = github.com/brian1917/illumioapi.Label {CreatedAt: "2020-05-31T18:18:44.378Z", CreatedBy: *github.com/brian1917/illumioapi.CreatedBy nil, Deleted: false,...+8 more}
(~R0.ptr) = (unreadable empty OP stack)
(~R0.ptr) = (unreadable empty OP stack)
(~R0.ptr) = (unreadable empty OP stack)
(~R0.ptr) = (unreadable empty OP stack)
(~R0.ptr) = (unreadable empty OP stack)
(~R0.ptr) = (unreadable empty OP stack)
(~R0.ptr) = (unreadable empty OP stack)
(~R0.ptr) = (unreadable empty OP stack)
(~R0.ptr) = (unreadable empty OP stack)
(~R0.ptr) = (unreadable empty OP stack)
(~R0.ptr) = (unreadable empty OP stack)
(~R0.ptr) = (unreadable empty OP stack)
(~R0.ptr) = (unreadable empty OP stack)
(~R0.ptr) = (unreadable empty OP stack)
~R0.ptr = (unreadable empty OP stack)
(~R0.len) = (unreadable empty OP stack)
(~R0.len) = (unreadable empty OP stack)
(~R0.len) = (unreadable empty OP stack)
(~R0.len) = (unreadable empty OP stack)
(~R0.len) = (unreadable empty OP stack)
(~R0.len) = (unreadable empty OP stack)
(~R0.len) = (unreadable empty OP stack)
(~R0.len) = (unreadable empty OP stack)
(~R0.len) = (unreadable empty OP stack)
(~R0.len) = (unreadable empty OP stack)
(~R0.len) = (unreadable empty OP stack)
(~R0.len) = (unreadable empty OP stack)
(~R0.len) = (unreadable empty OP stack)
(~R0.len) = (unreadable empty OP stack)
~R0.len = (unreadable empty OP stack)
(dlv) **print 0x2be73e**
2877246
(dlv) **print 0x9f900f**
10457103
(dlv)

**Comment by agwilkinson** [comment]
Any movement on this one ? I still get SIGSEGV upon exec using the latest code (10.0.7).

**Comment by brian1917** [comment]
@agwilkinson - can you try version 10.0.11 and see if this fixes the issue. re-open if it does not.

**Comment by agwilkinson** [comment]
same same

❯ **./workloader label-export**
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x9fb4a1]

goroutine 1 [running]:
github.com/brian1917/workloader/cmd/labelexport.exportLabels()
        /home/runner/work/workloader/workloader/cmd/labelexport/cmd.go:93 +0x7a1
github.com/brian1917/workloader/cmd/labelexport.glob..func1(0x1284640?, {0xb61eca?, 0x0?, 0x0?})
        /home/runner/work/workloader/workloader/cmd/labelexport/cmd.go:46 +0x15d
github.com/spf13/cobra.(*Command).execute(0x1284640, {0x12ce158, 0x0, 0x0})
        /home/runner/go/pkg/mod/github.com/spf13/cobra@v1.7.0/command.go:944 +0x847
github.com/spf13/cobra.(*Command).ExecuteC(0x127f2e0)
        /home/runner/go/pkg/mod/github.com/spf13/cobra@v1.7.0/command.go:1068 +0x3bd
github.com/spf13/cobra.(*Command).Execute(...)
        /home/runner/go/pkg/mod/github.com/spf13/cobra@v1.7.0/command.go:992
github.com/brian1917/workloader/cmd.Execute()
        /home/runner/work/workloader/workloader/cmd/root.go:243 +0x25
main.main()
        /home/runner/work/workloader/workloader/main.go:90 +0x6dc
