### ISSUE TITLE
loop-label-file ,consumer-and-provider & consolidate flags for traffic cmd

### ISSUE THREAD

**Issue by xmlisnotaprotocol** [brian1917/workloader#84]
traffic cmd does not have loop-label-file ,consumer-and-provider & consolidate flags that explorer cmd that it replaces does. A customer is asking for explorer cmd to be restored to v10 or those 3 options to be added to traffic

 .\workloader.exe explorer
2023-09-12 19:16:42  [WARNING] - this command has been renamed to traffic. please use "workloader traffic" in the future

**Comment by brian1917** [comment]
The old explorer command was restored until `traffic` has full backwards compatibility on this feature

**Comment by brian1917** [comment]
It was restored in 10.0.10
