### ISSUE TITLE
[BUG] Import Ruleset command fails because of a label ending with a space character.

### ISSUE THREAD

**Issue by cpainchaud** [brian1917/workloader#99]
From CSV file:
![image](https://github.com/brian1917/workloader/assets/6696638/7a746207-ee5b-4cfd-a30d-5a15f2fac846)

You cannot see it but label "Sharepoint 2013 " ends with a white space which Workloader seems to strip out so my import command fails:
![image](https://github.com/brian1917/workloader/assets/6696638/e8a11dd6-eb12-45da-9e56-f14be4ea1d14)

Note: I expect the issue will also happen on rule import later so may be you could have a look there too ?

Thank you

**Comment by brian1917** [comment]
Fixed.
